version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: win/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install selenium
          name: selenium
      - run:
          command: python 1.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
